apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-serve
spec:
  selector:
    matchLabels:
      app: gateway-serve
  template:
    metadata:
      labels:
        app: gateway-serve
    spec:
      containers:
      - name: gateway-serve
        image: gateway-eff-net:eff-net-v1
        # image: 071714138980.dkr.ecr.eu-west-2.amazonaws.com/efficient-net-eks:gateway-eff-net-eff-net-v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9696
        env:
        - name: TF_SERVING_HOST
          value: tf-serve-bird.default.svc.cluster.local:8500  # kubernates naming convention

