apiVersion: v1
kind: Service
metadata:
  name: tf-serve-bird
spec:
  type: ClusterIP  # default service type is always ClusterIP (i.e., internal service)
  selector:
    app: tf-serve-bird
  ports:
  - port: 8500
    targetPort: 8500