version: "3.9"
services:
  eff-net:
    image: zoomcamp-eff-net:eff-net-v1
  gateway:
    image: gateway-eff-net:eff-net-v1
    environment:
      - TF_SERVING_HOST=eff-net:8500
    ports:
      - "9696:9696"
  # gateway-windows:
  #   image: gateway-eff-net:eff-net-v1-windows
  #   environment:
  #     - TF_SERVING_HOST=eff-net:8500
  #   ports:
  #     - "9696:9696"